### ISSUE TITLE
[device support] Maxim DS3231

### ISSUE THREAD

**Issue by jsimmonds2** [nerves-time/nerves_time#68]
Congratulations on a lovely clean support of various I2C-based RTC devices ! 😃 
( i.e. not needing any Linux kernel-level support/driver )

I'd like to contribute a plugin for the Maxim **DS3231** device . . unless that's already planned | underway.

**Comment by fhunleth** [comment]
I don't know of anyone implementing an interface to that device, so that would be great if you could contribute! Thank you!!

Let us know if you have any trouble. When you're ready (assuming that you're interested in having it under the `nerves-time` GitHub org), let me know and I'll give you permissions.

**Comment by jsimmonds2** [comment]
Thanks ! Yes, totally happy to offer the DS3231 interface to `Nerves-Time` and also happy if an Org. Member creates the repo for it so I can just submit a PR with all the bits . . is that an Ok workflow ?

**Comment by fhunleth** [comment]
Done - you should get an email with access to an empty repository.

**Comment by jsimmonds2** [comment]
Thanks . . I'm underway.
Just noticed, though, that the other specific RTC support apps are organized with Vendor at the top. Are you concerned enough about uniform naming to want to change DS3231 to Maxim Integrated / DS3231 ?

**Comment by fhunleth** [comment]
I hadn't thought through the naming for this RTC. I think you should name your modules however you feel appropriate to start out, and then before we're ready to publish to hex, lets revisit.

**Comment by fhunleth** [comment]
Closing now that https://github.com/nerves-time/nerves_time_rtc_ds3231 exists.
